CREATE TABLE Posts
(
    PostID INT PRIMARY KEY IDENTITY,
    UserID INT,
    Caption NVARCHAR(MAX),
    ImageURL NVARCHAR(MAX),
    PostDate DATETIME DEFAULT GETDATE()
);


SELECT * FROM Posts;
DROP TABLE Posts;