CREATE TABLE Posts (
    PostID INT PRIMARY KEY IDENTITY,
    UserID INT FOREIGN KEY REFERENCES Users(UserID),
    Caption NVARCHAR(MAX),
    ImageURL NVARCHAR(MAX),
    PostDate DATETIME DEFAULT GETDATE()
);
